import 'package:carrental/services/auth_services.dart';
import 'package:flutter/material.dart';
// import 'tests/homescreen2.dart';
import 'screens/MainScreen.dart';

import 'package:mapbox_maps_flutter/mapbox_maps_flutter.dart' as mp;
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';

// import 'firebase_options.dart';
import 'authAndAdmin/welcome_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // to connect app with firebase project and it contains all the necessary configuration values

  // Abdalroaf
  await Firebase.initializeApp(
    // firebaseOptions it is used to initialize firebase with default options for current platform
    // this file generated by the FlutterFire CLI

    // options: DefaultFirebaseOptions.currentPlatform
  );

  // to set the access token for Mapbox SDK this token is
  // required to authenticate requests to Mapbox services
  mp.MapboxOptions.setAccessToken(
    '#####put the token here I remove the the one was here becouse the security issues by Abdalrouf',
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,

      home: const AuthGate(),
    );
  }
}

//const to build only in compile time
class AuthGate extends StatelessWidget {
  const AuthGate();
  // to check if user is logged in or not
  @override
  Widget build(BuildContext context) {
    // if there is any change in auth state it will rebuild the widget

    // FutureBuilder is used to build a widget based on the latest snapshot of interaction with a Future
    // it builds the widget only one time when the future completes
    // this why i use StreamBuilder instead of FutureBuilder

    // and if the user in aby screen the stream will notify the widget to rebuild when the auth state changes

    return StreamBuilder<User?>(
      // snapshot contains the user data if logged in or null if not logged in
      // it contans the latest auth state of the user
      // the firebase allows caching the auth state so that user remain logged in even after app is closed
      // it returns  a stream of User object or null
      stream: AuthService().authStateChanges,
      builder: (context, snapshot) {
        // while checking the auth state show loading indicator
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(
            backgroundColor: Color(0xFF0B1628),
            body: Center(child: CircularProgressIndicator()),
          );
        }
        // if user is not logged in show welcome screen
        final user = snapshot.data;
        if (user == null) return const WelcomeScreen();

        // if there is any error it will fall back to welcome screen

        // if user is logged in show home screen
        return const HomeScreen();
      },
    );
  }
}
